#!/usr/bin/env python3
"""Build the Worker: Rust -> wasm32 -> wasm-bindgen -> an uploadable module set.

This does the same job as `worker-build`, which is the official tool and the
one you should prefer if it installs on your machine. It does not install
everywhere: `worker-build` depends on `zstd-sys`, whose build script needs a C
toolchain, and on a Rust host that links with the bundled `rust-lld` rather
than an external linker (for example `x86_64-pc-windows-gnullvm` with no
Visual Studio present) that build script cannot link. This script needs only
Python, cargo, and the prebuilt `wasm-bindgen` binary.

The shim it emits is modelled on the one in `worker-build` (Cloudflare,
MIT/Apache-2.0). Two behaviours from it are load-bearing and deliberately
preserved:

* WebAssembly instances are wrapped so that a `RuntimeError` marks the module
  as needing reinitialisation. Without it, one trapping request leaves the
  isolate poisoned and every later request on it fails too.
* Durable Object classes are re-exported through the same wrapper, because the
  runtime looks them up as named exports of the entry module.

Usage:

    python scripts/build.py [--out build/worker] [--profile release]

Set WASM_BINDGEN to an explicit path if the binary is not on PATH.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys

TARGET = "wasm32-unknown-unknown"

# Exported by wasm-bindgen for the shim's own use; never wrapped as handlers.
SYSTEM_FNS = {"__worker_init_state", "__wbg_reset_state"}

# Handlers the runtime invokes with (arg, env, ctx) rather than as plain
# functions.
CONTEXT_HANDLERS = {"fetch", "queue", "scheduled", "email"}

SHIM_TEMPLATE = """// Generated by scripts/build.py. Do not edit.
//
// Modelled on the shim from Cloudflare's worker-build (MIT/Apache-2.0).
import { WorkerEntrypoint } from "cloudflare:workers";
import * as exports from "./index.js";

Error.stackTraceLimit = 100;
const initState = exports.__worker_init_state();

// A WebAssembly trap leaves the instance unusable. Without this, the first
// request to trap would poison the isolate and every subsequent request served
// by it would fail too, long after the original cause was gone.
function checkReinitialize() {
  if (initState.criticalError) {
    exports.__wbg_reset_state();
    initState.criticalError = false;
    initState.instanceId++;
  }
}

function handleMaybeCritical(e) {
  if (e instanceof WebAssembly.RuntimeError) {
    initState.criticalError = true;
  }
}

addEventListener("error", (e) => handleMaybeCritical(e.error));

class Entrypoint extends WorkerEntrypoint {}

__HANDLERS__

const instanceProxyHooks = {
  set: (t, p, v, r) => Reflect.set(t.instance, p, v, r),
  has: (t, p) => Reflect.has(t.instance, p),
  deleteProperty: (t, p) => Reflect.deleteProperty(t.instance, p),
  apply: (t, thisArg, args) => Reflect.apply(t.instance, thisArg, args),
  construct: (t, args, nt) => Reflect.construct(t.instance, args, nt),
  getPrototypeOf: (t) => Reflect.getPrototypeOf(t.instance),
  setPrototypeOf: (t, proto) => Reflect.setPrototypeOf(t.instance, proto),
  isExtensible: (t) => Reflect.isExtensible(t.instance),
  preventExtensions: (t) => Reflect.preventExtensions(t.instance),
  getOwnPropertyDescriptor: (t, p) => Reflect.getOwnPropertyDescriptor(t.instance, p),
  defineProperty: (t, p, d) => Reflect.defineProperty(t.instance, p, d),
  ownKeys: (t) => Reflect.ownKeys(t.instance),
};

const classProxyHooks = {
  construct(ctor, args, newTarget) {
    try {
      checkReinitialize();
      const holder = {
        instance: Reflect.construct(ctor, args, newTarget),
        instanceId: initState.instanceId,
        ctor,
        args,
        newTarget,
      };
      return new Proxy(holder, {
        ...instanceProxyHooks,
        get(target, prop, receiver) {
          // Rebuild against the current instance if the module was reset
          // underneath us, so a stale object cannot call into dead memory.
          if (target.instanceId !== initState.instanceId) {
            target.instance = Reflect.construct(target.ctor, target.args, target.newTarget);
            target.instanceId = initState.instanceId;
          }
          const original = Reflect.get(target.instance, prop, receiver);
          if (typeof original !== "function") return original;
          if (original.constructor === Function) {
            return new Proxy(original, {
              apply(fn, thisArg, argArray) {
                checkReinitialize();
                try {
                  return fn.apply(thisArg, argArray);
                } catch (e) {
                  handleMaybeCritical(e);
                  throw e;
                }
              },
            });
          }
          return new Proxy(original, {
            async apply(fn, thisArg, argArray) {
              checkReinitialize();
              try {
                return await fn.apply(thisArg, argArray);
              } catch (e) {
                handleMaybeCritical(e);
                throw e;
              }
            },
          });
        },
      });
    } catch (e) {
      initState.criticalError = true;
      throw e;
    }
  },
};

export default new Proxy(Entrypoint, classProxyHooks);
__CLASS_EXPORTS__
"""


def run(cmd, **kw):
    print("  $", " ".join(cmd))
    proc = subprocess.run(cmd, **kw)
    if proc.returncode != 0:
        raise SystemExit(f"command failed with exit {proc.returncode}: {' '.join(cmd)}")


def find_wasm_bindgen() -> str:
    explicit = os.environ.get("WASM_BINDGEN")
    if explicit:
        if not os.path.isfile(explicit):
            raise SystemExit(f"WASM_BINDGEN points at {explicit}, which does not exist")
        return explicit
    found = shutil.which("wasm-bindgen")
    if found:
        return found
    raise SystemExit(
        "wasm-bindgen not found. Install the prebuilt binary matching the\n"
        "wasm-bindgen version in Cargo.lock, from\n"
        "  https://github.com/rustwasm/wasm-bindgen/releases\n"
        "and either put it on PATH or set WASM_BINDGEN to its full path.\n"
        "The version must match Cargo.lock exactly or the generated glue will\n"
        "not match the module."
    )


def crate_wasm_name() -> str:
    """The .wasm filename cargo produces, derived from the package name."""
    with open("Cargo.toml", encoding="utf-8") as handle:
        for line in handle:
            m = re.match(r'^\s*name\s*=\s*"([^"]+)"', line)
            if m:
                return m.group(1).replace("-", "_") + ".wasm"
    raise SystemExit("could not read the package name from Cargo.toml")


def generate_shim(out_dir: str) -> None:
    index = os.path.join(out_dir, "index.js")
    with open(index, encoding="utf-8") as handle:
        content = handle.read()

    funcs = [
        name
        for name in re.findall(r"^export function\s+([A-Za-z0-9_$]+)\s*\(", content, re.M)
        if name not in SYSTEM_FNS
    ]
    classes = re.findall(r"^export class\s+([A-Za-z0-9_$]+)", content, re.M)

    handlers = []
    for name in funcs:
        if name in CONTEXT_HANDLERS:
            handlers.append(
                f"Entrypoint.prototype.{name} = function {name}(arg) {{\n"
                f"  return exports.{name}.call(this, arg, this.env, this.ctx);\n"
                f"}};"
            )
        else:
            handlers.append(f"Entrypoint.prototype.{name} = exports.{name};")

    class_exports = "\n".join(
        f"export const {c} = new Proxy(exports.{c}, classProxyHooks);" for c in classes
    )

    shim = SHIM_TEMPLATE.replace("__HANDLERS__", "\n".join(handlers)).replace(
        "__CLASS_EXPORTS__", class_exports
    )
    with open(os.path.join(out_dir, "shim.mjs"), "w", encoding="utf-8", newline="\n") as handle:
        handle.write(shim)

    print(f"  handlers: {', '.join(funcs) or '(none)'}")
    print(f"  classes:  {', '.join(classes) or '(none)'}")
    if "fetch" not in funcs:
        raise SystemExit(
            "No `fetch` export was produced. The crate needs a #[event(fetch)] "
            "handler, and it must be compiled for wasm32 (check any cfg gates)."
        )


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the Worker module set.")
    ap.add_argument("--out", default=os.path.join("build", "worker"))
    ap.add_argument("--profile", default="release", choices=["release", "dev"])
    args = ap.parse_args()

    if not os.path.isfile("Cargo.toml"):
        raise SystemExit("run this from the repository root")

    wb = find_wasm_bindgen()
    print(f"Using wasm-bindgen at {wb}")

    print("Building Rust -> wasm32...")
    cargo = ["cargo", "build", "--target", TARGET]
    if args.profile == "release":
        cargo.append("--release")
    run(cargo)

    wasm = os.path.join("target", TARGET, args.profile, crate_wasm_name())
    if not os.path.isfile(wasm):
        raise SystemExit(f"expected build output at {wasm}, which is not there")

    if os.path.isdir(args.out):
        shutil.rmtree(args.out)
    os.makedirs(args.out, exist_ok=True)

    print("Generating JS bindings...")
    run([wb, "--no-typescript", "--target", "module", "--out-name", "index", "--out-dir", args.out, wasm])

    print("Generating shim...")
    generate_shim(args.out)

    # wasm-bindgen creates this for inline JS snippets. An empty one would be
    # uploaded as nothing useful and only confuses the module list.
    snippets = os.path.join(args.out, "snippets")
    if os.path.isdir(snippets) and not any(os.scandir(snippets)):
        os.rmdir(snippets)

    print("\nBuilt:")
    total = 0
    for name in sorted(os.listdir(args.out)):
        full = os.path.join(args.out, name)
        if os.path.isfile(full):
            size = os.path.getsize(full)
            total += size
            print(f"  {name:20} {size / 1024:8.1f} KiB")
    print(f"  {'total':20} {total / 1024:8.1f} KiB")
    print(f"\nDeploy with:\n  python scripts/deploy.py --name <worker-name> --build-dir {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
