//! sing-box v1.13 JSON emitter.
//!
//! Produces a complete, runnable client config — `log`, a `mixed` inbound, the
//! node plus a `direct` outbound, and a `route` block — rather than a bare
//! outbound fragment, because a fragment cannot be validated by `sing-box
//! check` and therefore cannot be validated at all (§9.7: schema checking is a
//! fast path, execution is the authority).
//!
//! # Why this emitter is more conservative than the others
//!
//! sing-box decodes its configuration with `UnmarshalDisallowUnknownFields`.
//! An unrecognised key is not ignored and does not warn — it aborts the parse
//! with `json: unknown field "…"`, taking the whole config down. Every other
//! core in this project tolerates a speculative field. This one does not, so
//! nothing is emitted here that was not confirmed against the schema.
//!
//! # The XHTTP split this emitter must preserve
//!
//! Upstream sing-box has never implemented XHTTP in any release
//! (parameter-inventory §2). Hiddify and Karing ship patched forks that do.
//! [`crate::translate::gate`] already refuses XHTTP for
//! [`ClientTarget::SingBoxUpstream`] and [`ClientTarget::NekoBox`], and lets it
//! through for [`ClientTarget::Hiddify`] and [`ClientTarget::Karing`] — so this
//! emitter renders an `xhttp` transport rather than assuming "sing-box core
//! implies no XHTTP". Collapsing the two is exactly the oversimplification that
//! costs Hiddify and Karing users a working node.

use serde_json::{json, Map, Value};

use crate::config::model::{
    ClientTarget, Core, Flow, Mux, Node, Protocol, Security, TlsSettings, Transport, VmessCipher,
    XhttpMode,
};

use super::util::{host_or_server, normalise_path};

/// The transport-level host override, if this transport has one.
///
/// Distinct from the server address: a node may dial a bare "clean IP" while
/// the real hostname travels in the transport's `Host`. That hostname is what
/// SNI should name.
fn transport_host_of(node: &Node) -> Option<&str> {
    match &node.transport {
        Transport::Xhttp { host, .. }
        | Transport::WebSocket { host, .. }
        | Transport::HttpUpgrade { host, .. } => host.as_deref(),
        Transport::Grpc { .. } | Transport::Raw => None,
    }
}
use super::{gate, Dropped, Emit, EmitError, Emitted, Format};

/// Tag of the emitted `direct` outbound.
const DIRECT_TAG: &str = "direct";

/// Tag used when the node carries none. sing-box requires `route.final` to name
/// an existing outbound, so the tag cannot be left empty.
const FALLBACK_TAG: &str = "proxy";

/// Loopback-only listen address for the local proxy.
///
/// Deviation from sing-box's own default, which is `::` — binding every
/// interface turns a personal client into an open proxy for anyone on the same
/// network. Cost: a user who deliberately wants to share the proxy with another
/// device on the LAN must widen this by hand.
const LISTEN_ADDRESS: &str = "127.0.0.1";

/// Port for the mixed (SOCKS + HTTP) inbound. 2080 is what v2rayN, Hiddify and
/// Karing all default to, so an imported config lands where the user's other
/// tooling already points.
const LISTEN_PORT: u16 = 2080;

/// uTLS identity used when the node names none but one is structurally
/// required.
///
/// REALITY's handshake is generated by uTLS, and sing-box refuses to build the
/// outbound without it: `uTLS is required by reality client`. Chrome is the
/// least remarkable ClientHello on the wire.
const DEFAULT_UTLS_FINGERPRINT: &str = "chrome";

/// Renders a [`Node`] as sing-box v1.13 JSON.
#[derive(Debug, Clone, Copy, Default)]
pub struct SingBox;

impl Emit for SingBox {
    fn core(&self) -> Core {
        Core::SingBox
    }

    fn emit(&self, node: &Node, target: ClientTarget) -> Result<Emitted, EmitError> {
        // Contract point 1: the gate runs before anything is rendered, and its
        // refusal propagates unchanged. Its non-blocking findings are the
        // starting point of `dropped`, not a separate channel the caller has to
        // remember to merge.
        let mut dropped = gate(node, target, false)?;

        let tag = outbound_tag(node, &mut dropped);
        let proxy = proxy_outbound(node, target, &tag, false, &mut dropped)?;

        let config = json!({
            "log": { "level": "info", "timestamp": true },
            // AdGuard DNS over HTTPS as the default resolver. Prevents local
            // DNS leaks; sing-box resolves DoH natively via type "https".
            "dns": {
                // Plain-IP fallbacks let sing-box resolve the DoH hostname itself.
                "servers": [
                    { "tag": "adguard", "type": "https", "server": "https://dns.adguard-dns.com/dns-query" },
                    { "tag": "adguard-fallback-1", "type": "udp", "server": "94.140.14.14" },
                    { "tag": "adguard-fallback-2", "type": "udp", "server": "94.140.15.15" }
                ]
            },
            "inbounds": [ {
                "type": "mixed",
                "tag": "mixed-in",
                "listen": LISTEN_ADDRESS,
                "listen_port": LISTEN_PORT,
            } ],
            "outbounds": [
                proxy,
                // `direct` is what `route` falls back to for anything the rules
                // exclude. Emitted as an outbound rather than as a rule
                // `action` so the tag exists for the user to point a rule at.
                { "type": "direct", "tag": DIRECT_TAG },
            ],
            "route": route_block(&tag),
        });

        match serde_json::to_string_pretty(&config) {
            Ok(config) => Ok(Emitted { config, format: Format::Json, dropped }),
            Err(e) => Err(EmitError::Serialisation(e.to_string())),
        }
    }
}

/// Pick the outbound tag, keeping it distinct from the `direct` outbound.
///
/// sing-box rejects the whole config on a tag clash — `duplicate
/// outbound/endpoint tag: direct` — so a node the user happened to name
/// "direct" would otherwise produce a config that cannot load at all.
fn outbound_tag(node: &Node, dropped: &mut Vec<Dropped>) -> String {
    let trimmed = node.tag.trim();
    if trimmed.is_empty() {
        return FALLBACK_TAG.to_owned();
    }
    if trimmed == DIRECT_TAG {
        dropped.push(Dropped::new(
            "tag",
            format!(
                "Renamed to \"{trimmed}-{FALLBACK_TAG}\". sing-box refuses to load a config with \
                 two outbounds sharing a tag, and this config also contains the built-in \
                 \"direct\" outbound that rules fall back to."
            ),
        ));
        return format!("{trimmed}-{FALLBACK_TAG}");
    }
    trimmed.to_owned()
}

/// The routing block.
///
/// `geoip` and `geosite` rule *items* were removed in sing-box 1.12; a config
/// carrying them fails to parse on 1.13. The replacement is `rule_set`, which
/// needs a downloadable `.srs` and a `experimental.cache_file` to be useful —
/// neither of which this emitter can invent for the user. So it emits no
/// geo-rules at all rather than a broken or half-configured one, and everything
/// that is not DNS goes to the proxy.
fn route_block(tag: &str) -> Value {
    json!({
        "rules": [
            // Sniffing moved out of the inbound and became a rule action in
            // 1.11; the inbound `sniff` field is deprecated on 1.13. Without it
            // domain-based rules the user adds later would only ever see IPs.
            { "action": "sniff" },
            // `type: "dns"` outbounds are deprecated in favour of this action.
            { "protocol": "dns", "action": "hijack-dns" },
        ],
        "final": tag,
        "auto_detect_interface": true,
    })
}

/// Build the outbound for the node itself.
fn proxy_outbound(
    node: &Node,
    target: ClientTarget,
    tag: &str,
    enhanced: bool,
    dropped: &mut Vec<Dropped>,
) -> Result<Value, EmitError> {
    let mut o = Map::new();
    o.insert("tag".to_owned(), Value::String(tag.to_owned()));
    o.insert("server".to_owned(), Value::String(node.server.address.clone()));
    o.insert("server_port".to_owned(), Value::from(node.server.port));

    match &node.protocol {
        Protocol::Vless { uuid, flow } => {
            o.insert("type".to_owned(), Value::String("vless".to_owned()));
            o.insert("uuid".to_owned(), Value::String(uuid.clone()));
            if let Some(f) = vless_flow(*flow)? {
                o.insert("flow".to_owned(), Value::String(f.to_owned()));
            }
            o.insert("packet_encoding".to_owned(), Value::String(packet_encoding()));
        }
        Protocol::Vmess { uuid, cipher } => {
            o.insert("type".to_owned(), Value::String("vmess".to_owned()));
            o.insert("uuid".to_owned(), Value::String(uuid.clone()));
            o.insert("security".to_owned(), Value::String(vmess_security(*cipher).to_owned()));
            // Xray deleted `alterId`; sing-box still parses it and 0 is the only
            // value that means AEAD. Emitting it explicitly documents that this
            // is an AEAD-only node rather than one that forgot to say.
            o.insert("alter_id".to_owned(), Value::from(0));
            o.insert("packet_encoding".to_owned(), Value::String(packet_encoding()));
        }
        Protocol::Trojan { password } => {
            o.insert("type".to_owned(), Value::String("trojan".to_owned()));
            o.insert("password".to_owned(), Value::String(password.clone()));
            // No `packet_encoding` here: the field exists only on VLESS and
            // VMess, and on trojan it is an unknown field, i.e. a parse error.
        }
        Protocol::Shadowsocks { method, password } => {
            o.insert("type".to_owned(), Value::String("shadowsocks".to_owned()));
            o.insert("method".to_owned(), Value::String(method.wire_name().to_owned()));
            o.insert("password".to_owned(), Value::String(password.clone()));
        }
    }

    if matches!(node.protocol, Protocol::Shadowsocks { .. }) {
        // Shadowsocks is structurally different in sing-box and gets its own
        // path: no `transport`, no `tls`, only a SIP003 plugin.
        shadowsocks_carrier(node, &mut o, dropped)?;
    } else {
        if let Some(t) = transport_block(node, target, dropped)? {
            o.insert("transport".to_owned(), t);
        }
        if let Some(tls) = tls_block(node, enhanced, dropped) {
            o.insert("tls".to_owned(), tls);
        }
    }

    if let Some(mux) = multiplex_block(&node.protocol, &node.mux) {
        o.insert("multiplex".to_owned(), mux);
    }

    if let Some(via) = node.chain_via.as_deref().map(str::trim).filter(|v| !v.is_empty()) {
        o.insert("detour".to_owned(), Value::String(via.to_owned()));
        dropped.push(Dropped::new(
            "chain_via",
            format!(
                "Emitted as detour: \"{via}\". sing-box documents that when detour is set \"all \
                 other fields will be ignored\" — bind_interface, connect_timeout and \
                 domain_resolver on this outbound stop having any effect, silently. The hop named \
                 here must also exist as an outbound in the config you import this into; on its \
                 own this config will fail to dial."
            ),
        ));
    }

    Ok(Value::Object(o))
}

/// VLESS `flow`, or `None` to omit the key.
///
/// sing-box accepts exactly one non-empty value, `xtls-rprx-vision`.
/// `xtls-rprx-vision-udp443` is Xray-only; the gate already rates it
/// untranslatable for this core, and this arm is the belt to that braces —
/// silently downgrading it to plain Vision would change UDP/443 handling
/// without saying so.
fn vless_flow(flow: Flow) -> Result<Option<&'static str>, EmitError> {
    match flow {
        // Omitted rather than `""`: the two are equivalent here, and omitting
        // keeps the config free of a field that means nothing.
        Flow::None => Ok(None),
        Flow::Vision => Ok(Some("xtls-rprx-vision")),
        Flow::VisionUdp443 => Err(EmitError::Refused(vec![
            "xtls-rprx-vision-udp443 exists only in Xray — sing-box accepts only \
             xtls-rprx-vision. Block UDP/443 with a routing rule instead."
                .to_owned(),
        ])),
    }
}

/// The value emitted for `packet_encoding`.
///
/// §4 "Defaults that differ": this field is tri-state and its default is the
/// opposite of Xray's. Omitted or `null` means **xUDP enabled**; `""` means
/// disabled; `"xudp"`/`"packetaddr"` are the explicit forms. Because omission
/// and empty string are different states — and because a reader coming from an
/// Xray config will assume the Xray default — it is always written out.
///
/// `packetaddr` is deliberately never emitted: it encodes IP destinations only
/// and fails at runtime against a domain.
fn packet_encoding() -> String {
    "xudp".to_owned()
}

/// VMess cipher, in sing-box's spelling.
///
/// Note the ChaCha name differs from Xray's `chacha20-ietf-poly1305`; sing-box
/// wants `chacha20-poly1305` and rejects the other.
fn vmess_security(cipher: VmessCipher) -> &'static str {
    match cipher {
        VmessCipher::Auto => "auto",
        VmessCipher::Aes128Gcm => "aes-128-gcm",
        VmessCipher::Chacha20Poly1305 => "chacha20-poly1305",
        // Unlike Xray — which maps this to `auto` without a word — sing-box
        // honours `zero`, so the user gets the unauthenticated payload they
        // actually asked for.
        VmessCipher::Zero => "zero",
    }
}

/// The `transport` object, or `None` for a bare TCP dial.
fn transport_block(
    node: &Node,
    target: ClientTarget,
    dropped: &mut Vec<Dropped>,
) -> Result<Option<Value>, EmitError> {
    let server = node.server.address.as_str();
    match &node.transport {
        // sing-box has no transport container for plain TCP: absence *is* raw.
        Transport::Raw => Ok(None),

        Transport::WebSocket { path, host, heartbeat_secs } => {
            if *heartbeat_secs > 0 {
                dropped.push(Dropped::new(
                    "transport",
                    format!(
                        "The {heartbeat_secs}s WebSocket heartbeat was not emitted: sing-box's ws \
                         transport has no ping option at all (Xray's wsSettings.heartbeatPeriod \
                         has no counterpart). An idle connection through Cloudflare may be closed \
                         from the edge without the client noticing; traffic resumes on the next \
                         dial, so this costs a reconnection, not the node."
                    ),
                ));
            }
            Ok(Some(json!({
                "type": "ws",
                "path": normalise_path(path),
                // sing-box's ws transport has no dedicated `host` field — unlike
                // Xray, where putting Host in `headers` is deprecated. Here the
                // header *is* the mechanism.
                "headers": { "Host": host_or_server(host.as_deref(), server) },
            })))
        }

        Transport::HttpUpgrade { path, host } => Ok(Some(json!({
            "type": "httpupgrade",
            "host": host_or_server(host.as_deref(), server),
            "path": normalise_path(path),
        }))),

        Transport::Grpc { service_name, multi_mode } => {
            if *multi_mode {
                dropped.push(Dropped::new(
                    "transport",
                    "gRPC multi-mode was dropped: it is an Xray/mihomo extension that batches \
                     several buffers into one frame, and sing-box implements only standard gRPC. \
                     The node still works — it just does not get multi-mode's overhead saving, \
                     and the server must not require it."
                        .to_owned(),
                ));
            }
            Ok(Some(json!({ "type": "grpc", "service_name": service_name })))
        }

        Transport::Xhttp { mode, path, host } => {
            if !target.supports_xhttp() {
                // Unreachable through `emit`, which gates first. Kept because
                // the cost of getting this wrong is a config that loads
                // *something* for a transport the core cannot speak.
                return Err(EmitError::Refused(vec![format!(
                    "{} runs upstream sing-box, which has never implemented XHTTP in any version. \
                     Use Hiddify or Karing, which ship patched builds that do.",
                    target.name()
                )]));
            }
            dropped.push(Dropped::new(
                "transport",
                "Emitted for a patched sing-box fork (Hiddify / Karing), which upstream sing-box \
                 cannot parse — this config is not portable to a stock sing-box build. Only path, \
                 host and mode are emitted: the fork's XHTTP tuning keys (padding, \
                 sc-* limits, xmux) are not part of any published schema, and sing-box treats an \
                 unknown field as a fatal parse error, so guessing them would break the whole \
                 config rather than one setting. The fork's own defaults apply instead."
                    .to_owned(),
            ));
            Ok(Some(json!({
                "type": "xhttp",
                "host": host_or_server(host.as_deref(), server),
                "path": normalise_path(path),
                "mode": xhttp_mode(*mode),
            })))
        }
    }
}

fn xhttp_mode(mode: XhttpMode) -> &'static str {
    match mode {
        XhttpMode::PacketUp => "packet-up",
        XhttpMode::StreamUp => "stream-up",
        XhttpMode::StreamOne => "stream-one",
    }
}

/// Shadowsocks' carrier, which is a SIP003 plugin and never a transport.
///
/// §5: sing-box's shadowsocks outbound has **no `transport` field and no `tls`
/// field** — both are unknown keys, i.e. a hard parse error (confirmed:
/// `outbounds[0].tls: json: unknown field "tls"`). The only way to put
/// Shadowsocks on WebSocket is `plugin: "v2ray-plugin"` with `plugin_opts` as a
/// SIP003 semicolon string. That is a different framing from the `transport`
/// object, not a spelling of it.
fn shadowsocks_carrier(
    node: &Node,
    o: &mut Map<String, Value>,
    dropped: &mut Vec<Dropped>,
) -> Result<(), EmitError> {
    match &node.transport {
        Transport::Raw => {
            if !matches!(node.security, Security::None) {
                dropped.push(Dropped::new(
                    "security",
                    "TLS was dropped: a sing-box shadowsocks outbound has no tls field, and \
                     emitting one is a fatal parse error rather than a warning. Shadowsocks \
                     encrypts its own payload, so the connection is not in the clear — but the \
                     SNI, ALPN and fingerprint configured here are not sent, and the traffic no \
                     longer looks like TLS on the wire."
                        .to_owned(),
                ));
            }
            Ok(())
        }
        Transport::WebSocket { path, host, heartbeat_secs } => {
            if matches!(node.security, Security::Reality(_)) {
                return Err(EmitError::Refused(vec![
                    "REALITY cannot be carried by the v2ray-plugin, which is the only way a \
                     sing-box shadowsocks outbound can reach WebSocket. Use VLESS for a REALITY \
                     node."
                        .to_owned(),
                ]));
            }
            let server = node.server.address.as_str();
            let host = host_or_server(host.as_deref(), server);
            let path = normalise_path(path);
            let tls = matches!(node.security, Security::Tls(_));

            let mut opts = vec!["mode=websocket".to_owned()];
            if tls {
                // v2ray-plugin's TLS is a bare flag: it takes the SNI from
                // `host` and nothing else.
                opts.push("tls".to_owned());
            }
            opts.push(format!("host={}", sip003_escape(host)));
            opts.push(format!("path={}", sip003_escape(&path)));

            o.insert("plugin".to_owned(), Value::String("v2ray-plugin".to_owned()));
            o.insert("plugin_opts".to_owned(), Value::String(opts.join(";")));

            if let Security::Tls(t) = &node.security {
                report_tls_lost_to_sip003(t, dropped);
            }
            if *heartbeat_secs > 0 {
                dropped.push(Dropped::new(
                    "transport",
                    format!(
                        "The {heartbeat_secs}s WebSocket heartbeat was not emitted: neither \
                         sing-box's ws transport nor the v2ray-plugin exposes a ping interval. An \
                         idle connection may be closed at the Cloudflare edge; that costs a \
                         reconnection, not the node."
                    ),
                ));
            }
            Ok(())
        }
        // Refused rather than degraded on purpose. Dropping the transport would
        // leave a config that loads cleanly and then speaks the wrong protocol
        // to the server — the silent failure this whole module exists to
        // prevent. XHTTP here is already rated Broken by the conflict engine.
        other => Err(EmitError::Refused(vec![format!(
            "Shadowsocks over {} cannot be expressed in sing-box: the shadowsocks outbound has no \
             transport field, and the only plugin available is v2ray-plugin, which speaks \
             WebSocket. Use VLESS, VMess or Trojan for this transport, or give this node \
             WebSocket.",
            other.name()
        )])),
    }
}

/// Record the TLS detail that a SIP003 option string cannot carry.
fn report_tls_lost_to_sip003(t: &TlsSettings, dropped: &mut Vec<Dropped>) {
    let mut lost = Vec::new();
    if !t.alpn.is_empty() {
        lost.push("ALPN");
    }
    if t.fingerprint.is_some() {
        lost.push("the uTLS fingerprint");
    }
    if t.sni.is_some() {
        lost.push("a separate SNI (the plugin reuses the WebSocket Host as SNI)");
    }
    if t.allow_insecure {
        lost.push("allow-insecure — certificate verification stays ON");
    }
    if lost.is_empty() {
        return;
    }
    dropped.push(Dropped::new(
        "security",
        format!(
            "Shadowsocks TLS goes through the v2ray-plugin's SIP003 option string, which has no \
             field for {}. These settings were not emitted.",
            lost.join(", ")
        ),
    ));
}

/// Escape a SIP003 option value.
///
/// `;` separates options and `=` separates key from value, so a path or host
/// containing either would silently split into different options — producing a
/// plugin configuration the user never wrote. SIP003 defines backslash
/// escaping for exactly this.
fn sip003_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if c == ';' || c == '=' || c == '\\' {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// The `tls` object, or `None` when the node runs without it.
fn tls_block(node: &Node, enhanced: bool, dropped: &mut Vec<Dropped>) -> Option<Value> {
    match &node.security {
        Security::None => None,

        Security::Tls(t) => {
            let mut tls = Map::new();
            tls.insert("enabled".to_owned(), Value::Bool(true));
            // Shared with the other two emitters so the same node presents the
            // same SNI everywhere. An IP literal is never emitted, since it is
            // not a valid SNI and a server will reject it.
            if let Some(sni) = super::util::effective_sni(
                t.sni.as_deref(),
                transport_host_of(node),
                node.server.address.as_str(),
            ) {
                tls.insert("server_name".to_owned(), Value::String(sni.to_owned()));
            }

            // ALPN is transport-dependent, not global. Pinning h2 on a
            // WebSocket or HTTPUpgrade node leaves no HTTP/1.1 connection for
            // the upgrade handshake, so the node connects and then hangs —
            // which reads to a user as a dead server. See `util::default_alpn`.
            let alpn: Vec<&str> = if t.alpn.is_empty() {
                super::util::default_alpn(&node.transport)
                    .map(<[&str]>::to_vec)
                    .unwrap_or_default()
            } else {
                t.alpn.iter().map(String::as_str).collect()
            };
            if !alpn.is_empty() {
                tls.insert("alpn".to_owned(), json!(alpn));
            }
            if t.allow_insecure {
                // Not fatal here, unlike Xray, where the key was removed
                // outright — so it is passed through rather than dropped.
                tls.insert("insecure".to_owned(), Value::Bool(true));
                dropped.push(Dropped::new(
                    "allow_insecure",
                    "Emitted as tls.insecure. sing-box still accepts this, but it disables \
                     certificate verification entirely, so anyone able to intercept the \
                     connection can read it. The same node cannot be exported to current Xray at \
                     all, which rejects the setting."
                        .to_owned(),
                ));
            }
            if let Some(fp) = t.fingerprint.as_deref().filter(|f| !f.is_empty()) {
                tls.insert("utls".to_owned(), json!({ "enabled": true, "fingerprint": fp }));
            } else if enhanced {
                // Enhanced Reachability defaults the uTLS fingerprint to a
                // browser profile. sing-box has no equivalent of Xray's TLS
                // ClientHello fragment, so this is the only part of the
                // profile it can carry; nothing fragment-shaped is emitted.
                tls.insert(
                    "utls".to_owned(),
                    json!({ "enabled": true, "fingerprint": DEFAULT_UTLS_FINGERPRINT }),
                );
            }
            Some(Value::Object(tls))
        }

        Security::Reality(r) => {
            let fingerprint = r
                .fingerprint
                .as_deref()
                .filter(|f| !f.is_empty())
                .unwrap_or(DEFAULT_UTLS_FINGERPRINT);
            if r.fingerprint.is_none() {
                dropped.push(Dropped::new(
                    "fingerprint",
                    format!(
                        "No fingerprint was set, so \"{DEFAULT_UTLS_FINGERPRINT}\" was chosen. \
                         sing-box refuses to build a REALITY outbound without uTLS (\"uTLS is \
                         required by reality client\"), so this cannot be left empty. Set one \
                         explicitly if the server expects a particular ClientHello."
                    ),
                ));
            }
            Some(json!({
                "enabled": true,
                "server_name": r.server_name,
                // No `alpn` under REALITY: the borrowed handshake carries the
                // target site's own, and overriding it is what makes a REALITY
                // client stand out from the site it is imitating.
                "utls": { "enabled": true, "fingerprint": fingerprint },
                "reality": {
                    "enabled": true,
                    "public_key": r.public_key,
                    "short_id": r.short_id,
                },
            }))
        }
    }
}

/// The `multiplex` object, or `None`.
///
/// §7 sing-box: `multiplex` exists **only** on shadowsocks, trojan, vless and
/// vmess. On socks, http, direct, hysteria, tuic, shadowtls or ssh it is an
/// unknown field and a parse error. Every protocol in the model happens to be
/// one of the four today; the guard is explicit so that adding Hysteria2 or
/// TUIC to the model cannot quietly produce an unloadable config.
fn multiplex_block(protocol: &Protocol, mux: &Mux) -> Option<Value> {
    if !mux.enabled || !supports_multiplex(protocol) {
        return None;
    }
    let mut m = Map::new();
    m.insert("enabled".to_owned(), Value::Bool(true));
    // sing-box's own default is already h2mux; stated explicitly because the
    // three cores' multiplexing are different mechanisms and a reader comparing
    // configs needs to see which one this is.
    m.insert("protocol".to_owned(), Value::String("h2mux".to_owned()));
    if mux.concurrency > 0 {
        // Only `max_streams`. It is mutually exclusive with `max_connections`
        // and `min_streams`, and setting more than one sizing policy is
        // rejected.
        m.insert("max_streams".to_owned(), Value::from(mux.concurrency));
    }
    Some(Value::Object(m))
}

fn supports_multiplex(protocol: &Protocol) -> bool {
    matches!(
        protocol,
        Protocol::Vless { .. }
            | Protocol::Vmess { .. }
            | Protocol::Trojan { .. }
            | Protocol::Shadowsocks { .. }
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::model::{Endpoint, RealitySettings, SsMethod};

    fn node(protocol: Protocol, transport: Transport, security: Security) -> Node {
        Node {
            tag: "cf-node".into(),
            server: Endpoint { address: "edge.example.com".into(), port: 443 },
            protocol,
            transport,
            security,
            mux: Mux::default(),
            chain_via: None,
            worker_served: false,
        }
    }

    fn vless_ws() -> Node {
        node(
            Protocol::Vless { uuid: "b831381d-6324-4d53-ad4f-8cda48b30811".into(), flow: Flow::None },
            Transport::WebSocket { path: "/ws".into(), host: None, heartbeat_secs: 30 },
            Security::Tls(TlsSettings::default()),
        )
    }

    fn emit(n: &Node, t: ClientTarget) -> Emitted {
        SingBox.emit(n, t).expect("node should emit")
    }

    fn parse(e: &Emitted) -> Value {
        serde_json::from_str(&e.config).expect("emitter must produce valid JSON")
    }

    fn outbound(v: &Value) -> &Value {
        &v["outbounds"][0]
    }

    #[test]
    fn emits_a_complete_client_config_not_a_fragment() {
        let v = parse(&emit(&vless_ws(), ClientTarget::SingBoxUpstream));
        assert!(v["log"].is_object());
        assert_eq!(v["inbounds"][0]["type"], "mixed");
        assert_eq!(v["inbounds"][0]["listen"], LISTEN_ADDRESS);
        assert_eq!(v["outbounds"][1]["type"], "direct");
        assert_eq!(v["route"]["final"], "cf-node");
    }

    #[test]
    fn route_never_contains_the_rule_items_removed_in_1_12() {
        let v = parse(&emit(&vless_ws(), ClientTarget::SingBoxUpstream));
        let route = v["route"].to_string();
        assert!(!route.contains("geoip"), "geoip rule items fail to parse on 1.12+: {route}");
        assert!(!route.contains("geosite"), "geosite rule items fail to parse on 1.12+: {route}");
    }

    #[test]
    fn packet_encoding_is_always_explicit_on_vless_and_vmess() {
        // Omitted means xUDP-on, "" means off — the opposite of Xray's default,
        // so silence would be read wrongly by anyone porting a config.
        let v = parse(&emit(&vless_ws(), ClientTarget::SingBoxUpstream));
        assert_eq!(outbound(&v)["packet_encoding"], "xudp");

        let n = node(
            Protocol::Vmess { uuid: "u".into(), cipher: VmessCipher::Auto },
            Transport::Raw,
            Security::Tls(TlsSettings::default()),
        );
        let v = parse(&emit(&n, ClientTarget::SingBoxUpstream));
        assert_eq!(outbound(&v)["packet_encoding"], "xudp");
        assert_eq!(outbound(&v)["alter_id"], 0);
    }

    #[test]
    fn packet_encoding_is_absent_on_trojan_and_shadowsocks() {
        // The field does not exist there, and an unknown field is fatal.
        for p in [
            Protocol::Trojan { password: "pw".into() },
            Protocol::Shadowsocks { method: SsMethod::Aes256Gcm, password: "pw".into() },
        ] {
            let n = node(p, Transport::Raw, Security::None);
            let v = parse(&emit(&n, ClientTarget::SingBoxUpstream));
            assert!(
                outbound(&v).get("packet_encoding").is_none(),
                "packet_encoding must not reach this protocol: {}",
                outbound(&v)
            );
        }
    }

    #[test]
    fn xhttp_reaches_the_patched_forks_and_only_them() {
        let n = node(
            Protocol::Vless { uuid: "u".into(), flow: Flow::None },
            Transport::Xhttp { mode: XhttpMode::PacketUp, path: "/x".into(), host: None },
            Security::Tls(TlsSettings::default()),
        );

        for t in [ClientTarget::Hiddify, ClientTarget::Karing] {
            let e = emit(&n, t);
            let v = parse(&e);
            assert_eq!(outbound(&v)["transport"]["type"], "xhttp", "{}", t.name());
            assert_eq!(outbound(&v)["transport"]["mode"], "packet-up");
            assert!(
                e.dropped.iter().any(|d| d.reason.contains("not portable")),
                "the fork-only nature of this config must be reported"
            );
        }

        for t in [ClientTarget::SingBoxUpstream, ClientTarget::NekoBox] {
            assert!(
                matches!(SingBox.emit(&n, t), Err(EmitError::Refused(_))),
                "{} runs upstream sing-box, which has no XHTTP",
                t.name()
            );
        }
    }

    #[test]
    fn websocket_host_goes_in_headers_because_there_is_no_host_field() {
        let mut n = vless_ws();
        n.transport =
            Transport::WebSocket { path: "ws/".into(), host: Some("cdn.example".into()), heartbeat_secs: 0 };
        let v = parse(&emit(&n, ClientTarget::SingBoxUpstream));
        let t = &outbound(&v)["transport"];
        assert_eq!(t["type"], "ws");
        assert_eq!(t["path"], "/ws");
        assert_eq!(t["headers"]["Host"], "cdn.example");
        assert!(t.get("host").is_none());
    }

    #[test]
    fn websocket_heartbeat_is_reported_lost_rather_than_silently_ignored() {
        let e = emit(&vless_ws(), ClientTarget::SingBoxUpstream);
        assert!(
            e.dropped.iter().any(|d| d.field == "transport" && d.reason.contains("heartbeat")),
            "sing-box has no ws ping option; the user must be told: {:?}",
            e.dropped
        );
    }

    #[test]
    fn shadowsocks_over_websocket_uses_a_sip003_string_not_a_transport() {
        let n = node(
            Protocol::Shadowsocks { method: SsMethod::Aes256Gcm, password: "pw".into() },
            Transport::WebSocket { path: "/ss".into(), host: None, heartbeat_secs: 0 },
            Security::Tls(TlsSettings::default()),
        );
        let v = parse(&emit(&n, ClientTarget::SingBoxUpstream));
        let o = outbound(&v);
        assert_eq!(o["plugin"], "v2ray-plugin");
        assert_eq!(o["plugin_opts"], "mode=websocket;tls;host=edge.example.com;path=/ss");
        // Both of these are unknown fields on a shadowsocks outbound.
        assert!(o.get("transport").is_none());
        assert!(o.get("tls").is_none());
    }

    #[test]
    fn shadowsocks_refuses_a_transport_it_cannot_actually_speak() {
        for t in [
            Transport::Grpc { service_name: "s".into(), multi_mode: false },
            Transport::HttpUpgrade { path: "/u".into(), host: None },
        ] {
            let n = node(
                Protocol::Shadowsocks { method: SsMethod::Aes256Gcm, password: "pw".into() },
                t,
                Security::Tls(TlsSettings::default()),
            );
            assert!(
                matches!(SingBox.emit(&n, ClientTarget::SingBoxUpstream), Err(EmitError::Refused(_))),
                "silently dropping the transport would produce a node that connects and \
                 then speaks the wrong protocol"
            );
        }
    }

    #[test]
    fn shadowsocks_tls_loss_is_explained() {
        let n = node(
            Protocol::Shadowsocks { method: SsMethod::Aes256Gcm, password: "pw".into() },
            Transport::Raw,
            Security::Tls(TlsSettings::default()),
        );
        let e = emit(&n, ClientTarget::SingBoxUpstream);
        assert!(e.dropped.iter().any(|d| d.field == "security" && d.reason.len() > 40));
    }

    #[test]
    fn sip003_values_that_would_split_the_option_string_are_escaped() {
        assert_eq!(sip003_escape("/a;b=c"), "/a\\;b\\=c");
        assert_eq!(sip003_escape("plain"), "plain");
        assert_eq!(sip003_escape("back\\slash"), "back\\\\slash");
    }

    #[test]
    fn reality_always_carries_utls_because_sing_box_refuses_without_it() {
        let n = node(
            Protocol::Vless { uuid: "u".into(), flow: Flow::None },
            Transport::Raw,
            Security::Reality(RealitySettings {
                public_key: "pk".into(),
                short_id: "0123".into(),
                server_name: "www.microsoft.com".into(),
                fingerprint: None,
            }),
        );
        let e = emit(&n, ClientTarget::SingBoxUpstream);
        let v = parse(&e);
        let tls = &outbound(&v)["tls"];
        assert_eq!(tls["utls"]["enabled"], true);
        assert_eq!(tls["utls"]["fingerprint"], DEFAULT_UTLS_FINGERPRINT);
        assert_eq!(tls["reality"]["public_key"], "pk");
        assert!(tls.get("alpn").is_none(), "REALITY must not override the borrowed ALPN");
        assert!(e.dropped.iter().any(|d| d.field == "fingerprint"));
    }

    #[test]
    fn multiplex_is_emitted_only_where_sing_box_has_the_field() {
        let mut n = vless_ws();
        n.mux = Mux { enabled: true, concurrency: 8 };
        let v = parse(&emit(&n, ClientTarget::SingBoxUpstream));
        assert_eq!(outbound(&v)["multiplex"]["protocol"], "h2mux");
        assert_eq!(outbound(&v)["multiplex"]["max_streams"], 8);
        // Sizing policies are mutually exclusive; only one may appear.
        assert!(outbound(&v)["multiplex"].get("max_connections").is_none());
        assert!(outbound(&v)["multiplex"].get("min_streams").is_none());

        for p in [
            Protocol::Vless { uuid: "u".into(), flow: Flow::None },
            Protocol::Vmess { uuid: "u".into(), cipher: VmessCipher::Auto },
            Protocol::Trojan { password: "pw".into() },
            Protocol::Shadowsocks { method: SsMethod::Aes256Gcm, password: "pw".into() },
        ] {
            assert!(supports_multiplex(&p), "{} has a multiplex field", p.name());
        }
    }

    #[test]
    fn a_node_named_direct_is_renamed_rather_than_clashing() {
        let mut n = vless_ws();
        n.tag = "direct".into();
        let e = emit(&n, ClientTarget::SingBoxUpstream);
        let v = parse(&e);
        assert_eq!(outbound(&v)["tag"], "direct-proxy");
        assert_eq!(v["route"]["final"], "direct-proxy");
        assert!(e.dropped.iter().any(|d| d.field == "tag"));
    }

    #[test]
    fn an_empty_tag_still_produces_a_resolvable_route_final() {
        let mut n = vless_ws();
        n.tag = "   ".into();
        let v = parse(&emit(&n, ClientTarget::SingBoxUpstream));
        assert_eq!(outbound(&v)["tag"], FALLBACK_TAG);
        assert_eq!(v["route"]["final"], FALLBACK_TAG);
    }

    #[test]
    fn detour_reports_the_dial_fields_it_silently_nullifies() {
        let mut n = vless_ws();
        n.chain_via = Some("hop-1".into());
        let e = emit(&n, ClientTarget::SingBoxUpstream);
        let v = parse(&e);
        assert_eq!(outbound(&v)["detour"], "hop-1");
        let d = e
            .dropped
            .iter()
            .find(|d| d.field == "chain_via")
            .expect("the nullification must be reported");
        assert!(d.reason.contains("ignored"));
    }

    #[test]
    fn vision_udp443_is_refused_rather_than_downgraded() {
        assert!(matches!(vless_flow(Flow::VisionUdp443), Err(EmitError::Refused(_))));
        assert_eq!(vless_flow(Flow::Vision), Ok(Some("xtls-rprx-vision")));
        assert_eq!(vless_flow(Flow::None), Ok(None));
    }

    #[test]
    fn vmess_chacha_uses_sing_boxs_spelling_not_xrays() {
        // Xray writes chacha20-ietf-poly1305; sing-box rejects that name.
        assert_eq!(vmess_security(VmessCipher::Chacha20Poly1305), "chacha20-poly1305");
        assert_eq!(vmess_security(VmessCipher::Zero), "zero");
    }

    #[test]
    fn gate_refusals_propagate_unchanged() {
        let mut n = vless_ws();
        n.worker_served = true;
        n.transport = Transport::Grpc { service_name: "s".into(), multi_mode: true };
        assert!(matches!(SingBox.emit(&n, ClientTarget::Hiddify), Err(EmitError::Refused(_))));
    }

    #[test]
    fn gate_degradations_are_carried_into_the_output() {
        let mut n = vless_ws();
        n.worker_served = true;
        let e = emit(&n, ClientTarget::SingBoxUpstream);
        assert!(
            e.dropped.iter().any(|d| d.reason.contains("classifiers are trained")),
            "the conflict engine's WebSocket warning must survive: {:?}",
            e.dropped
        );
    }

    #[test]
    fn emitted_metadata_says_json() {
        let e = emit(&vless_ws(), ClientTarget::SingBoxUpstream);
        assert_eq!(e.format, Format::Json);
        assert_eq!(SingBox.core(), Core::SingBox);
    }
}

/// Tag of the selector group a multi-node config routes through.
const SELECTOR_TAG: &str = "select";

/// Render several nodes as one sing-box config.
///
/// Not a concatenation of single-node configs: sing-box takes one outbound
/// list and one `route.final`, so a multi-node export needs a `selector`
/// outbound for the user to switch between nodes in their client.
///
/// # Errors
/// [`EmitError::Refused`] when the list is empty, when the target does not run
/// sing-box, or when every node is rejected by [`gate`].
pub fn emit_nodes(nodes: &[Node], target: ClientTarget, enhanced: bool) -> Result<Emitted, EmitError> {
    if target.core() != Core::SingBox {
        return Err(EmitError::Refused(vec![format!(
            "{} runs {}, not sing-box, so a sing-box JSON config would not be read by it",
            target.name(),
            target.core().name()
        )]));
    }
    if nodes.is_empty() {
        return Err(EmitError::Refused(vec![
            "no nodes to export; a sing-box config with no proxy outbound has nothing to \
             proxy through"
                .to_owned(),
        ]));
    }

    let tags =
        crate::translate::util::unique_tags(nodes, &[DIRECT_TAG, SELECTOR_TAG], FALLBACK_TAG);
    let label = nodes.len() > 1;

    let mut dropped = Vec::new();
    let mut refusals = Vec::new();
    let mut outbounds = Vec::with_capacity(nodes.len() + 2);
    let mut usable_tags = Vec::new();

    for (node, tag) in nodes.iter().zip(&tags) {
        // Collect every node's reasons rather than stopping at the first: a
        // user fixing a ten-node export should see all ten problems at once.
        let mut node_dropped = match gate(node, target, enhanced) {
            Ok(f) => f,
            Err(EmitError::Refused(reasons)) => {
                refusals.extend(reasons.iter().map(|r| prefix(r, tag, label)));
                continue;
            }
            Err(other) => return Err(other),
        };
        match proxy_outbound(node, target, tag, enhanced, &mut node_dropped) {
            Ok(o) => {
                outbounds.push(o);
                usable_tags.push(tag.clone());
                dropped.extend(node_dropped.into_iter().map(|d| Dropped {
                    field: d.field,
                    reason: prefix(&d.reason, tag, label),
                }));
            }
            Err(EmitError::Refused(reasons)) => {
                refusals.extend(reasons.iter().map(|r| prefix(r, tag, label)));
            }
            Err(other) => return Err(other),
        }
    }

    if usable_tags.is_empty() {
        return Err(EmitError::Refused(refusals));
    }

    // A node that failed while others succeeded is reported rather than
    // silently missing from the user's client.
    dropped.extend(refusals.into_iter().map(|r| Dropped::new("node", r)));

    let mut members: Vec<Value> = usable_tags.iter().map(|t| Value::String(t.clone())).collect();
    members.push(Value::String(DIRECT_TAG.to_owned()));

    outbounds.push(json!({
        "type": "selector",
        "tag": SELECTOR_TAG,
        "outbounds": members,
        "default": usable_tags[0].clone(),
    }));
    outbounds.push(json!({ "type": "direct", "tag": DIRECT_TAG }));

    let config = json!({
        "log": { "level": "info", "timestamp": true },
        // AdGuard DNS over HTTPS as the default resolver. Prevents local
        // DNS leaks; sing-box resolves DoH natively via type "https".
        "dns": {
            // Plain-IP fallbacks let sing-box resolve the DoH hostname itself.
            "servers": [
                { "tag": "adguard", "type": "https", "server": "https://dns.adguard-dns.com/dns-query" },
                { "tag": "adguard-fallback-1", "type": "udp", "server": "94.140.14.14" },
                { "tag": "adguard-fallback-2", "type": "udp", "server": "94.140.15.15" }
            ]
        },
        "inbounds": [ {
            "type": "mixed",
            "tag": "mixed-in",
            "listen": LISTEN_ADDRESS,
            "listen_port": LISTEN_PORT,
        } ],
        "outbounds": outbounds,
        "route": route_block(SELECTOR_TAG),
    });

    match serde_json::to_string_pretty(&config) {
        Ok(config) => Ok(Emitted { config, format: Format::Json, dropped }),
        Err(e) => Err(EmitError::Serialisation(e.to_string())),
    }
}

/// Attach a node's tag to a message, but only when there is more than one node
/// to tell apart.
fn prefix(reason: &str, tag: &str, label: bool) -> String {
    if label {
        format!("{tag}: {reason}")
    } else {
        reason.to_owned()
    }
}

#[cfg(test)]
mod multi_node_tests {
    use super::*;
    use crate::config::model::{
        Endpoint, Flow, Mux, Protocol, Security, TlsSettings, Transport, XhttpMode,
    };

    fn node(tag: &str) -> Node {
        Node {
            tag: tag.to_owned(),
            server: Endpoint { address: "example.com".into(), port: 443 },
            protocol: Protocol::Vless {
                uuid: "01234567-89ab-cdef-0123-456789abcdef".into(),
                flow: Flow::None,
            },
            transport: Transport::WebSocket {
                path: "/ws".into(),
                host: None,
                heartbeat_secs: 0,
            },
            security: Security::Tls(TlsSettings {
                sni: Some("example.com".into()),
                ..TlsSettings::default()
            }),
            mux: Mux::default(),
            chain_via: None,
            worker_served: false,
        }
    }

    fn xhttp(tag: &str) -> Node {
        let mut n = node(tag);
        n.transport = Transport::Xhttp {
            mode: XhttpMode::PacketUp,
            path: "/x".into(),
            host: None,
        };
        n
    }

    fn parsed(nodes: &[Node]) -> Value {
        let e = emit_nodes(nodes, ClientTarget::SingBoxUpstream, false).expect("emits");
        serde_json::from_str(&e.config).expect("valid json")
    }

    #[test]
    fn several_nodes_become_a_selector_the_user_can_switch_with() {
        let v = parsed(&[node("tokyo"), node("paris")]);
        let outs = v["outbounds"].as_array().expect("array");
        // Two proxies, one selector, one direct.
        assert_eq!(outs.len(), 4);
        let selector = outs.iter().find(|o| o["type"] == "selector").expect("selector");
        assert_eq!(selector["outbounds"][0], "tokyo");
        assert_eq!(selector["outbounds"][1], "paris");
        assert_eq!(selector["outbounds"][2], "direct");
        assert_eq!(selector["default"], "tokyo");
        assert_eq!(v["route"]["final"], SELECTOR_TAG);
    }

    #[test]
    fn duplicate_tags_are_made_unique_rather_than_breaking_the_config() {
        // sing-box refuses the whole file on a tag clash, naming neither node.
        let v = parsed(&[node("same"), node("same")]);
        let tags: Vec<&str> = v["outbounds"]
            .as_array()
            .expect("array")
            .iter()
            .filter_map(|o| o["tag"].as_str())
            .collect();
        assert!(tags.contains(&"same"));
        assert!(tags.contains(&"same-2"));
    }

    #[test]
    fn a_node_named_after_a_reserved_outbound_is_renamed() {
        for reserved in [DIRECT_TAG, SELECTOR_TAG] {
            let v = parsed(&[node(reserved)]);
            let outs = v["outbounds"].as_array().expect("array");
            let proxy = outs.iter().find(|o| o["type"] == "vless").expect("proxy");
            assert_ne!(proxy["tag"], reserved);
        }
    }

    #[test]
    fn one_untranslatable_node_does_not_lose_the_others() {
        // The property that matters for a subscription: partial success beats
        // refusing everything, as long as the omission is reported.
        let e = emit_nodes(&[node("good"), xhttp("bad")], ClientTarget::SingBoxUpstream, false)
            .expect("emits");
        let v: Value = serde_json::from_str(&e.config).expect("valid json");
        let selector = v["outbounds"]
            .as_array()
            .expect("array")
            .iter()
            .find(|o| o["type"] == "selector")
            .expect("selector");
        assert_eq!(selector["outbounds"][0], "good");
        assert!(e.dropped.iter().any(|d| d.reason.contains("bad")));
    }

    #[test]
    fn an_empty_list_is_refused_rather_than_emitting_a_useless_config() {
        assert!(emit_nodes(&[], ClientTarget::SingBoxUpstream, false).is_err());
    }

    #[test]
    fn a_client_running_another_core_is_refused() {
        assert!(emit_nodes(&[node("a")], ClientTarget::V2rayN, false).is_err());
        assert!(emit_nodes(&[node("a")], ClientTarget::Mihomo, false).is_err());
    }

    #[test]
    fn every_node_failing_refuses_the_whole_export() {
        assert!(emit_nodes(&[xhttp("bad")], ClientTarget::SingBoxUpstream, false).is_err());
    }
}

/// Enhanced Reachability coverage. Off-state behaviour is pinned by the tests
/// above, which all emit with the flag off.
#[cfg(test)]
mod enhanced_tests {
    use super::*;
    use crate::config::model::{Endpoint, TlsSettings};

    fn vless_ws() -> Node {
        Node {
            tag: "cf-node".into(),
            server: Endpoint { address: "edge.example.com".into(), port: 443 },
            protocol: Protocol::Vless {
                uuid: "b831381d-6324-4d53-ad4f-8cda48b30811".into(),
                flow: Flow::None,
            },
            transport: Transport::WebSocket { path: "/ws".into(), host: None, heartbeat_secs: 30 },
            security: Security::Tls(TlsSettings::default()),
            mux: Mux::default(),
            chain_via: None,
            worker_served: false,
        }
    }

    /// sing-box has no equivalent of Xray's ClientHello fragment, so Enhanced
    /// Reachability must add a browser uTLS fingerprint and nothing else.
    #[test]
    fn enhanced_adds_a_browser_utls_and_nothing_else() {
        let off = emit_nodes(&[vless_ws()], ClientTarget::SingBoxUpstream, false)
            .expect("off emits");
        let on = emit_nodes(&[vless_ws()], ClientTarget::SingBoxUpstream, true)
            .expect("on emits");

        // No fragment-shaped field may appear anywhere in the output.
        assert!(!on.config.contains("fragment"));
        assert!(!on.config.contains("finalmask"));

        let off_v: Value = serde_json::from_str(&off.config).unwrap();
        let mut on_v: Value = serde_json::from_str(&on.config).unwrap();
        assert!(off_v["outbounds"][0]["tls"].get("utls").is_none());

        // The toggle's entire effect is the utls block.
        assert_eq!(
            on_v["outbounds"][0]["tls"]["utls"],
            json!({ "enabled": true, "fingerprint": DEFAULT_UTLS_FINGERPRINT })
        );
        on_v["outbounds"][0]["tls"].as_object_mut().unwrap().remove("utls");
        assert_eq!(on_v, off_v, "nothing else may change");
    }

    #[test]
    fn an_explicit_fingerprint_is_kept_under_enhanced() {
        let mut n = vless_ws();
        n.security = Security::Tls(TlsSettings {
            fingerprint: Some("firefox".into()),
            ..Default::default()
        });
        let e = emit_nodes(&[n], ClientTarget::SingBoxUpstream, true).expect("emits");
        let v: Value = serde_json::from_str(&e.config).unwrap();
        assert_eq!(
            v["outbounds"][0]["tls"]["utls"],
            json!({ "enabled": true, "fingerprint": "firefox" })
        );
    }
}
